clientside/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='clientside'


urlpatterns = [
    path('', views.Home, name = 'homepage'),
    path('about/', views.About, name = 'about'),
    path('services/', views.Services, name = 'services'),
    path('track/', views.Track, name = 'track'),
    path('contact/', views.Contact, name = 'contact'),  
    
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dreazy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientside.urls')),    
]

clientside/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

ORDERSTATUS = ((1, "Processed"),
               (2, "Dispatch"),
               (3, "En Route "),
               (4, "Delivered"),
               (5, "On Hold"),
               (6, "Cancelled"))

class user (models.Model):
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=10)
    
    def __str__(self):
        return self.username
    
class Order(models.Model):
    # sender information
    sender_name = models.CharField(max_length=50)
    sender_address = models.CharField(max_length=50)
    sender_email = models.EmailField()
    
    
    # Recievers information
    reciever_name = models.CharField(max_length=50, null=True, blank=True)
    Phone_number = models.CharField(null=True, blank=True, max_length=50)
    reciever_address = models.CharField(max_length=50, null=True, blank=True)
    reciever_email = models.EmailField()
   
    
    # Order information
    origin = models.CharField(max_length=50, null=True, blank=True)
    destination = models.CharField(max_length=50, null=True, blank=True)
    package = models.IntegerField(null=True)
    carrier = models.CharField(max_length=50, null=True, blank=True)
    type_of_shipment = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    reference_number = models.CharField(max_length=50, null=True, blank=True)
    weight = models.CharField(max_length=50, null=True, blank=True)
    departure_date = models.CharField(null=True, blank=True, max_length=50)
    arrival_date = models.CharField(null=True, blank=True, max_length=50)
    departure_time = models.CharField(null=True, blank=True, max_length=50)
    arrival_time = models.CharField(null=True, blank=True, max_length=50)
    payment_method = models.CharField(max_length=50, null=True, blank=True)  
    tracking_number = models.CharField(default=f"ATLAS{str(uuid.uuid4())[:18]}-ORDER", max_length=30, unique=True)
    status = models.IntegerField(choices=ORDERSTATUS, default=1)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable= False)
    date_added = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_added']
        
    def __str__(self):
        return f"{self.reciever_name} -Order- {self.get_status_display()}"
        
        
    def generate_tracking_number(self):
        uuid_string = str(uuid.uuid4().int)
        formatted_uuid = f"ATLAS{str(uuid.uuid4())[:18]}-ORDER"
        return formatted_uuid

    def save(self, *args, **kwargs):
        if not self.tracking_number:
            self.tracking_number = self.generate_tracking_number()
        super().save(*args, **kwargs)
       
    

    

clientside/forms.py
from django.forms import ModelForm

clientside/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Order

# Create your views here.

def Home(request):
    return render(request, 'homepage.html')

def About(request):
    return render(request, 'about.html')

def Services(request):
    return render(request, 'services.html')

def Track(request):
    if request.method == 'POST':
        tracking_number = request.POST.get('tracking_number')
        try:
            model_instance = Order.objects.get(tracking_number=tracking_number)
            return render(request, 'track_and_trace.html', {'model_instance': model_instance})
        except Order.DoesNotExist:
            messages.error(request, 'Order not found.')
    return render(request, 'track_and_trace.html')


def Contact(request):
    return render(request, 'contact.html')

clientside/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block about_active %} active {% endblock %}
{% block content %}
<main class="main">

  <!-- Page Title -->
  <div class="page-title" data-aos="fade"
    style="background-image: url({% static 'assets/img/about-page-title-bg.jpg' %});">
    <div class="container">
      <h1>About</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a href="{% url 'clientside:homepage' %}">Home</a></li>
          <li class="current">About</li>
        </ol>
      </nav>
    </div>
  </div><!-- End Page Title -->

  <!-- About Section -->
  <section id="about" class="about section">

    <div class="container">

      <div class="row gy-4" data-aos="fade-up" data-aos-delay="100">
        <div class="col-lg-5">
          <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-7" data-aos="fade-up" data-aos-delay="200">
          <div class="content">
            <h3>Our Goal and Story</h3>
            <p>
              Swift Courier is a leading logistics company dedicated to providing efficient and reliable shipping and
              transportation
              solutions. With years of industry experience, we have built a reputation for excellence, customer
              satisfaction, and a
              commitment to meeting the diverse needs of our clients.
            </p>
            <ul>
              <li><i class="bi bi-check-circle-fill"></i> <span>Transparency and open communication</span></li>
              <li><i class="bi bi-check-circle-fill"></i> <span>We are committed to delivering exceptional
                  service</span></li>
              <li><i class="bi bi-check-circle-fill"></i> <span>Experience reliability and efficiency</span></li>
            </ul>
          </div>
        </div>
      </div>

    </div>

  </section><!-- /About Section -->

  <!-- Why Us Section -->
  <section id="why-us" class="why-us section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Why Choose Us</h2>

    </div><!-- End Section Title -->

    <div class="container">

      <div class="row g-0">

        <div class="col-xl-5 img-bg" data-aos="fade-up" data-aos-delay="100">
          <img src="{% static 'assets/img/why-us-bg.jpg' %}" alt="">
        </div>

        <div class="col-xl-7 slides position-relative" data-aos="fade-up" data-aos-delay="200">

          <div class="swiper">
            <script type="application/json" class="swiper-config">
                {
                  "loop": true,
                  "speed": 600,
                  "autoplay": {
                    "delay": 5000
                  },
                  "slidesPerView": "auto",
                  "centeredSlides": true,
                  "pagination": {
                    "el": ".swiper-pagination",
                    "type": "bullets",
                    "clickable": true
                  },
                  "navigation": {
                    "nextEl": ".swiper-button-next",
                    "prevEl": ".swiper-button-prev"
                  }
                }
              </script>
            <div class="swiper-wrapper">

              <div class="swiper-slide">
                <div class="item">
                  <h3 class="mb-3">Let's grow your business together</h3>
                  <h4 class="mb-3">Experience reliability and efficiency
                  </h4>
                  <p>Contact us today to discuss how we can support your logistics requirements and contribute to the
                    success of your
                    business.</p>
                </div>
              </div><!-- End slide item -->

              <div class="swiper-slide">
                <div class="item">
                  <h3 class="mb-3">We are committed to delivering exceptional service</h3>
                  <h4 class="mb-3">Transparency and open communication</h4>
                  <p>Are fundamental values for us. We believe in building strong and collaborative relationships with
                    our
                    clients, based on trust, integrity, and mutual success. </p>
                </div>
              </div><!-- End slide item -->

              <div class="swiper-slide">
                <div class="item">
                  <h3 class="mb-3">Our Network</h3>
                  <h4 class="mb-3">Extensive global network
                  </h4>
                  <p>Our extensive global network of partners and carriers enables us to offer comprehensive coverage
                    and reach in numerous
                    countries and regions worldwide.</p>
                </div>
              </div><!-- End slide item -->

            </div>
            <div class="swiper-pagination"></div>
          </div>

          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>

      </div>

    </div>

  </section><!-- /Why Us Section -->

  <!-- Call To Action Section -->
  <section id="call-to-action" class="call-to-action section">

    <img src="{% static 'assets/img/cta-bg.jpg' %}" alt="">

    <div class="container">
      <div class="row justify-content-center" data-aos="zoom-in" data-aos-delay="100">
        <div class="col-xl-10">
          <div class="text-center">
            <h3>Track Your Package</h3>
            <p>Dedicated to providing efficient and reliable shipping and transportation solutions.we have built a
              reputation for excellence, customer satisfaction, and a commitment to meeting the diverse needs of our
              clients.</p>
            <a class="cta-btn" href="{% url 'clientside:track' %}">Track Your Package</a>
          </div>
        </div>
      </div>
    </div>

  </section><!-- /Call To Action Section -->

</main>
{% endblock %}

clientside/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Atlas logistics</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet">

  <!-- Vendor CSS Files -->

  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">


  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  {% block css %}

  {% endblock css %}
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top bg-dark">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="#" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Atlas logistics</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a class="{% block homepage_active %}{% endblock %}" href="{% url 'clientside:homepage' %}">Home<br></a>
          </li>
          <li><a class="{% block about_active %}{% endblock %}" href="{% url 'clientside:about' %}">About</a></li>
          <li><a class="{% block services_active %}{% endblock %}" href="{% url 'clientside:services' %}">Services</a>
          </li>
          <li><a class="{% block track_and_trace_active %}{% endblock %}" href="{% url 'clientside:track' %}">Track and
              Trace</a></li>
          <li><a class="{% block contact_active %}{% endblock %}" href="{% url 'clientside:contact' %}">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>

  <main class="main">

    {% block hero %}
    {% endblock %}

    {% block content %}
    {% endblock %}



  </main>

  <footer id="footer" class="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-about">
            <a href="#" class="logo d-flex align-items-center">
              <span class="sitename">Atlas logistics</span>
            </a>
            <p>We are a team striving to deliver exceptional results with integrity and
            expertise.Contact us today and let us take care of your logistics needs.</p>
            <div class="social-links d-flex mt-4">
              <a href=""><i class="bi bi-twitter-x"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a href="{% url 'clientside:homepage' %}">Home</a></li>
              <li><a href="{% url 'clientside:about' %}">About us</a></li>
              <li><a href="{% url 'clientside:services' %}">Services</a></li>
              <li><a href="#">Terms of service</a></li>
              <li><a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><a href="{% url 'clientside:services' %}">Logistics</a></li>
              <li><a href="{% url 'clientside:services' %}">Trucking</a></li>
              <li><a href="{% url 'clientside:services' %}">Warehousing </a></li>
              <li><a href="{% url 'clientside:services' %}">Packaging</a></li>
              <li><a href="{% url 'clientside:services' %}">Storage</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>your adress </p>
            <p>######, #####</p>
            <p class="mt-4"><strong>Phone:</strong> <span>##### # ### ####</span></p>
            <p><strong>Email:</strong> <span>info@example.com</span></p>
          </div>

        </div>
      </div>
    </div>

    <div class="container copyright text-center">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Atlas logistics</strong> <span>All Rights
          Reserved</span></p>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

clientside/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block contact_active %} active {% endblock %}
{% block content %}

<main class="main">

  <!-- Page Title -->
  <div class="page-title" data-aos="fade" style="background-image: url(assets/img/contact-page-title-bg.jpg);">
    <div class="container">
      <h1>Contact</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a href="{% url 'clientside:homepage' %}">Home</a></li>
          <li class="current">Contact</li>
        </ol>
      </nav>
    </div>
  </div><!-- End Page Title -->

  <!-- Contact Section -->
  <section id="contact" class="contact section">

    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">

      <div class="row gy-4">

        <div class="col-lg-5">
          <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="200">
            <i class="bi bi-geo-alt flex-shrink-0"></i>
            <div>
              <h3>Address</h3>
              <p>###, ### ###, ####</p>
            </div>
          </div><!-- End Info Item -->

          <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
            <i class="bi bi-telephone flex-shrink-0"></i>
            <div>
              <h3>Call Us</h3>
              <p>### #### ### ##</p>
            </div>
          </div><!-- End Info Item -->

          <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
            <i class="bi bi-envelope flex-shrink-0"></i>
            <div>
              <h3>Email Us</h3>
              <p>info@example.com</p>
            </div>
          </div><!-- End Info Item -->

        </div>

        <div class="col-lg-7">
          <form action="forms/contact.php" method="post" class="php-email-form" data-aos="fade-up" data-aos-delay="500">
            <div class="row gy-4">

              <div class="col-md-6">
                <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
              </div>

              <div class="col-md-6 ">
                <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
              </div>

              <div class="col-md-12">
                <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
              </div>

              <div class="col-md-12">
                <textarea class="form-control" name="message" rows="6" placeholder="Message" required=""></textarea>
              </div>

              <div class="col-md-12 text-center">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>

                <button type="submit">Send Message</button>
              </div>

            </div>
          </form>
        </div><!-- End Contact Form -->

      </div>

    </div>

  </section><!-- /Contact Section -->

</main>
{% endblock %}